# chart-repo: stable/prometheus
# chart-version: latest

nameOverride: prometheus

server:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - prometheus.demo.nalbam.com

alertmanager:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - alertmanager-prometheus.demo.nalbam.com
